- name: Upload vhost configs
  become: yes
  template: src=vhost_conf.j2 dest=/etc/nginx/sites-enabled/{{item}}.conf
  vars:
   vhost: "{{item}}"
  with_items: "{{vhosts}}"
  notify:
      - restart nginx

