- name: Remove user wothout password
  block:
   - name: Check user wothout password
     shell: mysql -u root -proot -e "SELECT count(*) FROM  mysql.user WHERE password = '';" | egrep [0-9]+  
     register: result
     changed_when: false
   - name: Remove user wothout password
     shell: mysql -u root -proot -e "DELETE FROM  mysql.user WHERE password = '';"  
     when: result.stdout != "0"

